# Generated by Django 3.2.15 on 2022-08-18 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=2)),
                ('postal', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('address2', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('order', models.IntegerField()),
                ('code', models.CharField(max_length=10)),
                ('cname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=2)),
                ('postal', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('address2', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('taxpayer', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('fed_id', models.CharField(max_length=30)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='deduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=1)),
                ('order', models.IntegerField()),
                ('pretax', models.BooleanField()),
                ('w2box14', models.BooleanField()),
                ('percent', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('code', models.CharField(max_length=10)),
                ('cname', models.CharField(max_length=30)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.company')),
            ],
        ),
        migrations.CreateModel(
            name='earning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=1)),
                ('order', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('code', models.CharField(max_length=10)),
                ('cname', models.CharField(max_length=30)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.company')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.department')),
            ],
        ),
        migrations.CreateModel(
            name='statetax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sui_rate', models.DecimalField(decimal_places=8, max_digits=10)),
                ('state', models.CharField(max_length=2)),
                ('sui_id', models.CharField(max_length=30)),
                ('state_id', models.CharField(max_length=30)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.company')),
            ],
        ),
        migrations.CreateModel(
            name='shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('shift_name', models.CharField(max_length=30)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.company')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.unit')),
            ],
        ),
        migrations.CreateModel(
            name='localitytax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locality_rate', models.DecimalField(decimal_places=8, max_digits=10)),
                ('locality', models.CharField(max_length=30)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.company')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.company'),
        ),
        migrations.CreateModel(
            name='bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routing', models.CharField(max_length=30, null=True)),
                ('bank_name', models.CharField(max_length=30, null=True)),
                ('account', models.CharField(max_length=30, null=True)),
                ('aba', models.CharField(max_length=10, null=True)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.company')),
            ],
        ),
        migrations.CreateModel(
            name='agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=2)),
                ('postal', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('address2', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('payee', models.CharField(max_length=30)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.company')),
            ],
        ),
    ]
