# Generated by Django 3.2.15 on 2022-08-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0003_auto_20220830_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='description',
        ),
        migrations.AddField(
            model_name='branch',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='code',
            field=models.CharField(max_length=10),
        ),
    ]
