# Generated by Django 3.2.15 on 2022-08-18 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=2)),
                ('postal', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('address2', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('paytype', models.CharField(max_length=1)),
                ('taxid', models.CharField(max_length=30)),
                ('birthdate', models.CharField(max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=1)),
                ('payrate', models.DecimalField(decimal_places=3, max_digits=10)),
                ('gender', models.CharField(max_length=1)),
                ('middle_name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('timeclock_id', models.CharField(max_length=30)),
                ('card_id', models.DecimalField(decimal_places=0, max_digits=10)),
                ('last_name', models.CharField(max_length=30)),
                ('taxid_type', models.CharField(max_length=3)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.company')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.department')),
                ('localitytax', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='entity.localitytax')),
                ('statetax', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='entity.statetax')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.unit')),
            ],
        ),
        migrations.CreateModel(
            name='garnishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuing_phone', models.CharField(max_length=30)),
                ('end_date', models.DateField()),
                ('amount_type', models.CharField(max_length=1)),
                ('limitamount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('isactive', models.BooleanField()),
                ('issuing_name', models.CharField(max_length=30)),
                ('orderid', models.CharField(max_length=30)),
                ('caseid', models.CharField(max_length=30)),
                ('release_date', models.DateField()),
                ('start_date', models.DateField()),
                ('issuing_title', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.agency')),
            ],
        ),
        migrations.CreateModel(
            name='emprate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=3, max_digits=10)),
                ('isactive', models.BooleanField()),
                ('paytype', models.CharField(max_length=1)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ants.employee')),
                ('shift_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.shift')),
            ],
        ),
    ]
